# You can use this to store API keys, mail server settings,
# or any other kind of configuration data that your application needs.
# In order to keep your production settings secret, store the production
# copy of this file on your server under shared/config/config.yml and copy
# it on deployment with this Capistrano task:#

# task :copy_config_files do
#   filename = "config/config.yml"
#   run "cp #{shared_path}/#{filename} #{release_path}/#{filename}"
# end
# after "deploy:update_code", :copy_config_files

development: &non_production_settings
  paypal:
    login:      magnol_1351263382_biz_api1.hotmail.com
    password:   1351263438
    signature:  AFcWxV21C7fd0v3bYYYRCpSSRl31AlmTUbskilNRZj-HSJl0-UYtCZfV

test:
  <<: *non_production_settings

production:
  encryption_key: someRandomBINARYKEY
  paypal:
    login:      magnol_1351263382_biz_api1.hotmail.com
    password:   1351263438
    signature:  AFcWxV21C7fd0v3bYYYRCpSSRl31AlmTUbskilNRZj-HSJl0-UYtCZfV
  
  # paypal:
  #   login:      magnolias_api1.parbros.net
  #   password:   ZBXKJJ7MXBV4CHPD
  #   signature:  A-sqeF2nkwwFawrGjvy0h5e0gEHRAqtgTreAzTQofNJvUZfbiHHFm8yN